version: "3"

services:
  rpc-twitter:
    tty: true
    image: rpc-twitter:1.0
    network_mode: bridge
    restart: unless-stopped
    ports:
    - '50055:50055'
    command: [ "make", "run-twitter"]
